package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonAuth generated by hbm2java
 */
@Entity
@Table(name = "COMMON_DTREE_LOCNAME")
public class CommonDtreeLocName implements java.io.Serializable {

	private Long id;
	private String codeId;
	private CommonDtree commonDtree;
	private String name;
	private String editId;
	private String editDate;
	private String editTime;

	public CommonDtreeLocName() {
	}

	public CommonDtreeLocName(Long id,String name,
			CommonDtree commonDtree, String codeId, String editId, String editDate,
			String editTime) {
		this.id = id;
		this.name = name;
		this.commonDtree = commonDtree;
		this.codeId = codeId;
		this.editId = editId;
		this.editDate = editDate;
		this.editTime = editTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_DTREE_LOCNAME_SEQ")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dtreeId")
	public CommonDtree getCommonDtree() {
		return this.commonDtree;
	}

	public void setCommonDtree(CommonDtree commonDtree) {
		this.commonDtree = commonDtree;
	}

	@Column(length = 20)
	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}
	
	@Column(columnDefinition="nvarchar(50)")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "editId", length = 50)
	public String getEditId() {
		return this.editId;
	}

	public void setEditId(String editId) {
		this.editId = editId;
	}

	@Column(name = "editDate", length = 8)
	public String getEditDate() {
		return this.editDate;
	}

	public void setEditDate(String editDate) {
		this.editDate = editDate;
	}

	@Column(name = "editTime", length = 6)
	public String getEditTime() {
		return this.editTime;
	}

	public void setEditTime(String editTime) {
		this.editTime = editTime;
	}

}
