package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Transient;

/**
 * CommonDepartment generated by hbm2java
 */
@Entity
@Table(name = "BASE_UNIT_INFO", uniqueConstraints = @UniqueConstraint(columnNames = "unitId"))
public class CommonDepartment extends BaseModel implements java.io.Serializable {

	private static final long serialVersionUID = -2425555721861459261L;
	private Integer id;
	private Integer parentId;
	private Integer level;
	private String unitCode;
	private String unitType;
	private String unitId;
	private String fundUnitId;
	private String unitFullName;
	private String unitShortName;
	private String unitEnglishName;
	private String unitZoneId;
	private String unitZoneName;
	private String unitStartIp;
	private String unitEndIp;
	private String unitZip;
	private String unitMailingAddress;
	private String unitPhoneNum;
	private String unitMobileNum;
	private String unitFaxNum;
	private String unitWebsite;
	private String unitManagerId;
	private String unitManagerName;
	private String unitEmail;
	private String unitLanguageId;
	private String unitCountryId;
	private String unitNote;
	private String unitStatus;

	public CommonDepartment() {
	}

	public CommonDepartment(Integer id, String unitId) {
		this.id = id;
		this.unitId = unitId;
	}

	public CommonDepartment(Integer id, String unitCode, String unitCountryId,
			String unitEnglishName, String unitWebsite, Integer parentId,
			Integer lev, String unitId, String fundUnitId, String unitFullName,
			String unitShortName, String unitZoneId, String unitZoneName,
			String unitStartIp, String unitEndIp, String unitZip,
			String unitMailingAddress, String unitType, String unitPhoneNum,
			String unitMobileNum, String unitFaxNum, String unitManagerId,
			String unitManagerName, String unitEmail, String unitLanguageId,
			String unitNote, String unitStatus, String createId,
			String createDate, String createTime, String updateId,
			String updateDate, String updateTime, String updateIp,
			String updateUnitShortName) {
		super(createId, createDate, createTime, updateId, updateDate,
				updateTime, updateIp, updateUnitShortName);
		this.id = id;
		this.parentId = parentId;
		this.level = lev;
		this.unitId = unitId;
		this.unitType = unitType;
		this.unitCode = unitCode;
		this.unitCountryId = unitCountryId;
		this.fundUnitId = fundUnitId;
		this.unitEnglishName = unitEnglishName;
		this.unitWebsite = unitWebsite;
		this.unitFullName = unitFullName;
		this.unitShortName = unitShortName;
		this.unitZoneId = unitZoneId;
		this.unitZoneName = unitZoneName;
		this.unitStartIp = unitStartIp;
		this.unitEndIp = unitEndIp;
		this.unitZip = unitZip;
		this.unitMailingAddress = unitMailingAddress;
		this.unitPhoneNum = unitPhoneNum;
		this.unitMobileNum = unitMobileNum;
		this.unitFaxNum = unitFaxNum;
		this.unitManagerId = unitManagerId;
		this.unitManagerName = unitManagerName;
		this.unitEmail = unitEmail;
		this.unitLanguageId = unitLanguageId;
		this.unitNote = unitNote;
		this.unitStatus = unitStatus;

		this.createId = createId;
		this.createDate = createDate;
		this.createTime = createTime;
		this.updateId = updateId;
		this.updateIp = updateIp;
		this.updateDate = updateDate;
		this.updateTime = updateTime;
		this.updateUnitShortName = updateUnitShortName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	@SequenceGenerator(name = "id", sequenceName = "COMMON_centerFullName_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "parentId")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "lev")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer lev) {
		this.level = lev;
	}
	@Column(name = "unitCode", length = 3)
	public String getUnitCode() {
		return unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}
	@Column(name = "unitType", length = 1)
	public String getUnitType() {
		return unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}
	@Column(name = "unitId", length = 4)
	public String getUnitId() {
		return unitId;
	}
	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}
	@Column(name = "unitFullName", length = 50)
	public String getUnitFullName() {
		return unitFullName;
	}

	public void setUnitFullName(String unitFullName) {
		this.unitFullName = unitFullName;
	}
	@Column(name = "unitShortName", length = 10)
	public String getUnitShortName() {
		return unitShortName;
	}

	public void setUnitShortName(String unitShortName) {
		this.unitShortName = unitShortName;
	}
	@Column(name = "unitZoneId", length = 5)
	public String getUnitZoneId() {
		return unitZoneId;
	}

	public void setUnitZoneId(String unitZoneId) {
		this.unitZoneId = unitZoneId;
	}
	@Column(name = "unitZoneName", length = 20)
	public String getUnitZoneName() {
		return unitZoneName;
	}

	public void setUnitZoneName(String unitZoneName) {
		this.unitZoneName = unitZoneName;
	}
	@Column(name = "unitStartIp", length = 16)
	public String getUnitStartIp() {
		return unitStartIp;
	}

	public void setUnitStartIp(String unitStartIp) {
		this.unitStartIp = unitStartIp;
	}
	@Column(name = "unitEndIp", length = 16)
	public String getUnitEndIp() {
		return unitEndIp;
	}

	public void setUnitEndIp(String unitEndIp) {
		this.unitEndIp = unitEndIp;
	}
	@Column(name = "unitZip", length = 5)
	public String getUnitZip() {
		return unitZip;
	}

	public void setUnitZip(String unitZip) {
		this.unitZip = unitZip;
	}
	@Column(name = "unitMailingAddress", length = 140)
	public String getUnitMailingAddress() {
		return unitMailingAddress;
	}

	public void setUnitMailingAddress(String unitMailingAddress) {
		this.unitMailingAddress = unitMailingAddress;
	}
	@Column(name = "unitPhoneNum", length = 20)
	public String getUnitPhoneNum() {
		return unitPhoneNum;
	}

	public void setUnitPhoneNum(String unitPhoneNum) {
		this.unitPhoneNum = unitPhoneNum;
	}
	@Column(name = "unitMobileNum", length = 20)
	public String getUnitMobileNum() {
		return unitMobileNum;
	}

	public void setUnitMobileNum(String unitMobileNum) {
		this.unitMobileNum = unitMobileNum;
	}
	@Column(name = "unitFaxNum", length = 20)
	public String getUnitFaxNum() {
		return unitFaxNum;
	}

	public void setUnitFaxNum(String unitFaxNum) {
		this.unitFaxNum = unitFaxNum;
	}
	@Column(name = "unitManagerId", length = 10)
	public String getUnitManagerId() {
		return unitManagerId;
	}

	public void setUnitManagerId(String unitManagerId) {
		this.unitManagerId = unitManagerId;
	}
	@Column(name = "unitManagerName", length = 10)
	public String getUnitManagerName() {
		return unitManagerName;
	}

	public void setUnitManagerName(String unitManagerName) {
		this.unitManagerName = unitManagerName;
	}
	@Column(name = "unitEmail", length = 50)
	public String getUnitEmail() {
		return unitEmail;
	}

	public void setUnitEmail(String unitEmail) {
		this.unitEmail = unitEmail;
	}
	@Column(name = "unitWebsite", length = 100)
	public String getUnitWebsite() {
		return unitWebsite;
	}

	public void setUnitWebsite(String unitWebsite) {
		this.unitWebsite = unitWebsite;
	}
	@Column(name = "unitLanguageId", length = 5)
	public String getUnitLanguageId() {
		return unitLanguageId;
	}

	public void setUnitLanguageId(String unitLanguageId) {
		this.unitLanguageId = unitLanguageId;
	}
	@Column(name = "unitNote", length = 500)
	public String getUnitNote() {
		return unitNote;
	}

	public void setUnitNote(String unitNote) {
		this.unitNote = unitNote;
	}
	@Column(name = "unitStatus", length = 5)
	public String getUnitStatus() {
		return unitStatus;
	}

	public void setUnitStatus(String unitStatus) {
		this.unitStatus = unitStatus;
	}
	@Column(name = "unitEnglishName", length = 100)
	public String getUnitEnglishName() {
		return unitEnglishName;
	}

	public void setUnitEnglishName(String unitEnglishName) {
		this.unitEnglishName = unitEnglishName;
	}
	@Column(name = "unitCountryId", length = 5)
	public String getUnitCountryId() {
		return unitCountryId;
	}

	public void setUnitCountryId(String unitCountryId) {
		this.unitCountryId = unitCountryId;
	}
	@Column(name = "fundUnitId", length = 4)
	public String getFundUnitId() {
		return fundUnitId;
	}

	public void setFundUnitId(String fundUnitId) {
		this.fundUnitId = fundUnitId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CommonDepartment [id=");
		builder.append(id);
		builder.append(", parentId=");
		builder.append(parentId);
		builder.append(", level=");
		builder.append(level);
		builder.append(", unitCode=");
		builder.append(unitCode);
		builder.append(", unitType=");
		builder.append(unitType);
		builder.append(", unitId=");
		builder.append(unitId);
		builder.append(", fundUnitId=");
		builder.append(fundUnitId);
		builder.append(", unitFullName=");
		builder.append(unitFullName);
		builder.append(", unitShortName=");
		builder.append(unitShortName);
		builder.append(", unitZoneId=");
		builder.append(unitZoneId);
		builder.append(", unitZoneName=");
		builder.append(unitZoneName);
		builder.append(", unitStartIp=");
		builder.append(unitStartIp);
		builder.append(", unitEndIp=");
		builder.append(unitEndIp);
		builder.append(", unitZip=");
		builder.append(unitZip);
		builder.append(", unitMailingAddress=");
		builder.append(unitMailingAddress);
		builder.append(", unitPhoneNum=");
		builder.append(unitPhoneNum);
		builder.append(", unitMobileNum=");
		builder.append(unitMobileNum);
		builder.append(", unitFaxNum=");
		builder.append(unitFaxNum);
		builder.append(", unitManagerId=");
		builder.append(unitManagerId);
		builder.append(", unitManagerName=");
		builder.append(unitManagerName);
		builder.append(", unitEmail=");
		builder.append(unitEmail);
		builder.append(", unitWebsite=");
		builder.append(unitWebsite);
		builder.append(", unitLanguageId=");
		builder.append(unitLanguageId);
		builder.append(", unitNote=");
		builder.append(unitNote);
		builder.append(", unitStatus=");
		builder.append(unitStatus);
		builder.append(", unitEnglishName=");
		builder.append(unitEnglishName);
		builder.append(", unitCountryId=");
		builder.append(unitCountryId);
		builder.append("]");
		return builder.toString();
	}

	@Transient
	public String getDepartmentCode() {
		return this.unitId;
	}

	public void setDepartmentCode(String departmentCode) {
		this.unitId = departmentCode;
	}

	@Transient
	public String getDepartment() {
		return this.unitFullName;
	}

	public void setDepartment(String department) {
		this.unitFullName = department;
	}

	@Transient
	public String getShortCode() {
		return this.unitId;
	}

	public void setShortCode(String shortCode) {
		this.unitId = shortCode;
	}

	@Transient
	public String getShortName() {
		return this.unitShortName;
	}

	public void setShortName(String shortName) {
		this.unitShortName = shortName;
	}

	@Transient
	public String getFullName() {
		return this.unitFullName;
	}

	public void setFullName(String fullName) {
		this.unitFullName = fullName;
	}

	@Transient
	public String getFullCode() {
		return this.unitId;
	}

	public void setFullCode(String fullCode) {
		this.unitId = fullCode;
	}

	@Transient
	public String getPreFullCode() {
		return this.unitId;
	}

	public void setPreFullCode(String preFullCode) {
		this.unitId = preFullCode;
	}

	@Transient
	public String getPhone() {
		return this.unitPhoneNum;
	}

	public void setPhone(String phone) {
		this.unitPhoneNum = phone;
	}

	@Transient
	public String getFax() {
		return this.unitFaxNum;
	}

	public void setFax(String fax) {
		this.unitFaxNum = fax;
	}

	@Transient
	public String getZip() {
		return this.unitZip;
	}

	public void setZip(String zip) {
		this.unitZip = zip;
	}

	@Transient
	public String getAddress() {
		return this.unitMailingAddress;
	}

	public void setAddress(String address) {
		this.unitMailingAddress = address;
	}

	@Transient
	public String getEmail() {
		return this.unitEmail;
	}

	public void setEmail(String email) {
		this.unitEmail = email;
	}

	@Transient
	public String getNotes() {
		return this.unitNote;
	}

	public void setNotes(String notes) {
		this.unitNote = notes;
	}

	@Transient
	public String getHomepage() {
		return null;
	}

	public void setHomepage(String homepage) {
		// this.homepage = homepage;
	}

	@Transient
	public String getChiefTitle() {
		return null;
	}

	public void setChiefTitle(String chiefTitle) {
		// this.chiefTitle = chiefTitle;
	}

	@Transient
	public String getChiefName() {
		return this.unitManagerName;
	}

	public void setChiefName(String chiefName) {
		this.unitManagerName = chiefName;
	}

	@Transient
	public String getIsSchool() {
		return null;
	}

	public void setIsSchool(String isSchool) {
		// this.isSchool = isSchool;
	}

	@Transient
	public String getSchoolType() {
		return null;
	}

	public void setSchoolType(String schoolType) {
		// this.schoolType = schoolType;
	}

}
