package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonVisitLogWeek generated by hbm2java
 */
@Entity
@Table(name = "COMMON_VISITLOG_WEEK")
public class CommonVisitLogWeek implements java.io.Serializable {

	private static final long serialVersionUID = -1205098146607807525L;
	private Long id;
	private String logYyy;
	private int logWeek;
	private Long logCount;

	public CommonVisitLogWeek() {
	}

	public CommonVisitLogWeek(Long id, String logYyy, int logWeek) {
		this.id = id;
		this.logYyy = logYyy;
		this.logWeek = logWeek;
	}

	public CommonVisitLogWeek(Long id, String logYyy, int logWeek,
			Long logCount) {
		this.id = id;
		this.logYyy = logYyy;
		this.logWeek = logWeek;
		this.logCount = logCount;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_VisitLogWeek_SEQ")	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "logYYY", nullable = false, length = 3)
	public String getLogYyy() {
		return this.logYyy;
	}

	public void setLogYyy(String logYyy) {
		this.logYyy = logYyy;
	}

	@Column(name = "logWeek", nullable = false)
	public int getLogWeek() {
		return this.logWeek;
	}

	public void setLogWeek(int logWeek) {
		this.logWeek = logWeek;
	}

	@Column(name = "logCount", scale = 0)
	public Long getLogCount() {
		return this.logCount;
	}

	public void setLogCount(Long logCount) {
		this.logCount = logCount;
	}

}
