package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * CommonAuditLogHistory generated by hbm2java
 */
@Entity
@Table(name = "COMMON_AUDITLOG_HISTORY")
public class CommonAuditLogHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7811542669306474367L;
	private String id;
	private String progCode;
	private String progName;
	private String logDate;
	private String logTime;
	private String userId;
	private String userName;
	private String userIp;
	private String methodName;
	private String entity;
	private String queryString;
	private String queryValues;
	private String exceptionMessage;

	public CommonAuditLogHistory() {
	}

	public CommonAuditLogHistory(String id) {
		this.id = id;
	}

	public CommonAuditLogHistory(String id, String progCode, String progName,
			String logDate, String logTime, String userId, String userName,
			String userIp, String methodName, String entity, String queryString,
			String queryValues, String exceptionMessage) {
		this.id = id;
		this.progCode = progCode;
		this.progName = progName;
		this.logDate = logDate;
		this.logTime = logTime;
		this.userId = userId;
		this.userName = userName;
		this.userIp = userIp;
		this.methodName = methodName;
		this.entity = entity;
		this.queryString = queryString;
		this.queryValues = queryValues;
		this.exceptionMessage = exceptionMessage;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "progCode", length = 50)
	public String getProgCode() {
		return this.progCode;
	}

	public void setProgCode(String progCode) {
		this.progCode = progCode;
	}

	@Column(name = "progName", length = 250)
	public String getProgName() {
		return this.progName;
	}

	public void setProgName(String progName) {
		this.progName = progName;
	}

	@Column(name = "logDate", length = 7)
	public String getLogDate() {
		return this.logDate;
	}

	public void setLogDate(String logDate) {
		this.logDate = logDate;
	}

	@Column(name = "logTime", length = 6)
	public String getLogTime() {
		return this.logTime;
	}

	public void setLogTime(String logTime) {
		this.logTime = logTime;
	}

	@Column(name = "userId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "userIp", length = 50)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "methodName", length = 200)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	@Column(name = "entity")
	@Type(type = "org.hibernate.type.MaterializedClobType") 
	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	@Column(name = "queryString")
	@Type(type = "org.hibernate.type.MaterializedClobType")
	public String getQueryString() {
		return this.queryString;
	}

	public void setQueryString(String queryString) {
		this.queryString = queryString;
	}

	@Column(name = "queryValues")
	@Type(type = "org.hibernate.type.MaterializedClobType")
	public String getQueryValues() {
		return this.queryValues;
	}

	public void setQueryValues(String queryValues) {
		this.queryValues = queryValues;
	}

	@Column(name = "exceptionMessage")
	@Type(type = "org.hibernate.type.MaterializedClobType")
	public String getExceptionMessage() {
		return this.exceptionMessage;
	}

	public void setExceptionMessage(String exceptionMessage) {
		this.exceptionMessage = exceptionMessage;
	}

}
