package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonAuth generated by hbm2java
 */
@Entity
@Table(name = "COMMON_AUTH")
public class CommonAuth implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2463911894933795940L;
	private Long id;
	private CommonGroup commonGroup;
	private CommonDtree commonDtree;
	private int auth;
	private String editId;
	private String editDate;
	private String editTime;

	public CommonAuth() {
	}

	public CommonAuth(Long id, int auth) {
		this.id = id;
		this.auth = auth;
	}

	public CommonAuth(Long id, CommonGroup commonGroup,
			CommonDtree commonDtree, int auth, String editId, String editDate,
			String editTime) {
		this.id = id;
		this.commonGroup = commonGroup;
		this.commonDtree = commonDtree;
		this.auth = auth;
		this.editId = editId;
		this.editDate = editDate;
		this.editTime = editTime;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_AUTH_SEQ")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupId")
	public CommonGroup getCommonGroup() {
		return this.commonGroup;
	}

	public void setCommonGroup(CommonGroup commonGroup) {
		this.commonGroup = commonGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dtreeId")
	public CommonDtree getCommonDtree() {
		return this.commonDtree;
	}

	public void setCommonDtree(CommonDtree commonDtree) {
		this.commonDtree = commonDtree;
	}

	@Column(name = "auth", nullable = false)
	public int getAuth() {
		return this.auth;
	}

	public void setAuth(int auth) {
		this.auth = auth;
	}

	@Column(name = "editId", length = 50)
	public String getEditId() {
		return this.editId;
	}

	public void setEditId(String editId) {
		this.editId = editId;
	}

	@Column(name = "editDate", length = 7)
	public String getEditDate() {
		return this.editDate;
	}

	public void setEditDate(String editDate) {
		this.editDate = editDate;
	}

	@Column(name = "editTime", length = 6)
	public String getEditTime() {
		return this.editTime;
	}

	public void setEditTime(String editTime) {
		this.editTime = editTime;
	}

}
