package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonNewslog generated by hbm2java
 */
@Entity
@Table(name = "COMMON_NEWS_LOG")
public class CommonNewsLog implements java.io.Serializable {

	private static final long serialVersionUID = -2078717765988680950L;
	private Long id;
	private CommonNews commonNews;
	private String userId;
	private String logDate;
	private String logTime;

	public CommonNewsLog() {
	}

	public CommonNewsLog(Long id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public CommonNewsLog(Long id, CommonNews commonNews, String userId,
			String logDate, String logTime) {
		this.id = id;
		this.commonNews = commonNews;
		this.userId = userId;
		this.logDate = logDate;
		this.logTime = logTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_NEWS_LOG_SEQ")		
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "newsId")
	public CommonNews getCommonNews() {
		return this.commonNews;
	}

	public void setCommonNews(CommonNews commonNews) {
		this.commonNews = commonNews;
	}

	@Column(name = "userId", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "logDate", length = 7)
	public String getLogDate() {
		return this.logDate;
	}

	public void setLogDate(String logDate) {
		this.logDate = logDate;
	}

	@Column(name = "logTime", length = 6)
	public String getLogTime() {
		return this.logTime;
	}

	public void setLogTime(String logTime) {
		this.logTime = logTime;
	}

}
