package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CommonUserRole generated by hbm2java
 */
@Entity
@Table(name = "COMMON_USERROLE")
public class CommonUserRole implements java.io.Serializable {

	private static final long serialVersionUID = -4889375306176975819L;
	private Integer id;
	private CommonUser commonUser;
	private CommonGroup commonGroup;
	private Integer roleId;
	private String editId;
	private String editDate;
	private String editTime;

	public CommonUserRole() {
	}

	public CommonUserRole(CommonUser commonUser) {
		this.commonUser = commonUser;
	}

	public CommonUserRole(CommonUser commonUser, CommonGroup commonGroup,
			Integer roleId, String editId, String editDate, String editTime) {
		this.commonUser = commonUser;
		this.commonGroup = commonGroup;
		this.roleId = roleId;
		this.editId = editId;
		this.editDate = editDate;
		this.editTime = editTime;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "commonUser"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public CommonUser getCommonUser() {
		return this.commonUser;
	}

	public void setCommonUser(CommonUser commonUser) {
		this.commonUser = commonUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupId")
	public CommonGroup getCommonGroup() {
		return this.commonGroup;
	}

	public void setCommonGroup(CommonGroup commonGroup) {
		this.commonGroup = commonGroup;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "editId", length = 50)
	public String getEditId() {
		return this.editId;
	}

	public void setEditId(String editId) {
		this.editId = editId;
	}

	@Column(name = "editDate", length = 7)
	public String getEditDate() {
		return this.editDate;
	}

	public void setEditDate(String editDate) {
		this.editDate = editDate;
	}

	@Column(name = "editTime", length = 6)
	public String getEditTime() {
		return this.editTime;
	}

	public void setEditTime(String editTime) {
		this.editTime = editTime;
	}
	
	private int[] roleIdArray = new int[] {1,2,3};
	private String[] roleName = new String[] {"一般使用者","業務管理者","系統管理者"};
	
	@Transient
	public String getRoleName() {
		for (int i=0; i<roleIdArray.length; i++) {
			if (i==getRoleId()) return roleName[i];
		}
		return "";
	}
	
	@Transient
	public String getRoleOption() {
        StringBuilder sb = new StringBuilder().append("<option value=''></option>");		
		for (int i=0; i<roleIdArray.length; i++) {
            sb.append("<option value='").append(roleIdArray[i]).append("' ");
            if (getRoleId() == roleIdArray[i]) sb.append(" selected ");
            sb.append(">").append(roleName[i]).append("</option>\n");    			
		}
		return sb.toString();
	}
	
	/**
	 * 若不是管理者，一律回傳field_RO
	 * <br>否則回傳原始的傳入的adminCssClass
	 * @param adminCssClass
	 * @return
	 */
	@Transient
	public String getCssClass(String adminCssClass) {
		if (getRoleId()>2) {
			return adminCssClass;
		} else {
			if (adminCssClass.indexOf("field_Q")!=-1) return "field_QRO";
			else return "field_RO";
		}
	}
	
	@Transient
	public boolean isUserLevel() {
		if (getRoleId()>1) return false;
		else return true;
	}	

}
