package com.kangdainfo.common.model.bo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.CascadeType;
import javax.persistence.OrderBy;

/**
 * CommonCodekind generated by hbm2java
 */
@Entity
@Table(name = "COMMON_CATALOG", uniqueConstraints = @UniqueConstraint(columnNames = "catalogId"))
public class CommonCatalog extends BaseModel implements java.io.Serializable {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8561723108597696615L;
	private Integer id;
	private String catalogId;
	private String catalogName;
	private Set<CommonCodeKind> commonCodeKinds = new HashSet<CommonCodeKind>(0);

	public CommonCatalog() {
	}

	public CommonCatalog(Integer id, String catalogId, String catalogName) {
		this.id = id;
		this.catalogId = catalogId;
		this.catalogName = catalogName;
	}

	public CommonCatalog(Integer id, String catalogId, String catalogName,
			Set<CommonCodeKind> commonCodeKinds) {
		this.id = id;
		this.catalogId = catalogId;
		this.catalogName = catalogName;
		this.commonCodeKinds = commonCodeKinds;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_CATALOG_SEQ")	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "catalogId", unique = true, nullable = false, length = 50)
	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "catalogName", nullable = false, length = 500)
	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonCatalog", cascade = CascadeType.ALL)	
	@OrderBy("codeKindId asc")
	public Set<CommonCodeKind> getCommonCodeKinds() {
		return this.commonCodeKinds;
	}

	public void setCommonCodeKinds(Set<CommonCodeKind> commonCodeKinds) {
		this.commonCodeKinds = commonCodeKinds;
	}

}
