package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * CommonAuditLog generated by hbm2java
 */
@Entity
@Table(name = "COMMON_AUDITLOG")
public class CommonAuditLog extends BaseModel implements java.io.Serializable {

	private static final long serialVersionUID = 2530193439583148637L;
	private String id;
	private String progCode;
	private String progName;
	private String logDate;
	private String logTime;
	private String methodName;
	private String entity;
	private String exceptionMessage;

	public CommonAuditLog() {
	}

	public CommonAuditLog(String id) {
		this.id = id;
	}

	public CommonAuditLog(String id, String progCode, String progName,
			String logDate, String logTime, String methodName, String entity,
			String exceptionMessage, String createId, String createDate,
			String createTime, String updateIp, String updateTime,
			String updateDate, String updateId, String updateUnitShortName) {
		this.id = id;
		this.progCode = progCode;
		this.progName = progName;
		this.logDate = logDate;
		this.logTime = logTime;
		this.methodName = methodName;
		this.entity = entity;
		this.exceptionMessage = exceptionMessage;
		this.createId = createId;
		this.createDate = createDate;
		this.createTime = createTime;
		this.updateId = updateId;
		this.updateDate = updateDate;
		this.updateTime = updateTime;
		this.updateIp = updateIp;
		this.updateUnitShortName = updateUnitShortName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "progCode", length = 50)
	public String getProgCode() {
		return this.progCode;
	}

	public void setProgCode(String progCode) {
		this.progCode = progCode;
	}

	@Column(name = "progName", length = 250)
	public String getProgName() {
		return this.progName;
	}

	public void setProgName(String progName) {
		this.progName = progName;
	}

	@Column(name = "logDate", length = 7)
	public String getLogDate() {
		return this.logDate;
	}

	public void setLogDate(String logDate) {
		this.logDate = logDate;
	}

	@Column(name = "logTime", length = 6)
	public String getLogTime() {
		return this.logTime;
	}

	public void setLogTime(String logTime) {
		this.logTime = logTime;
	}

	@Column(name = "methodName", length = 200)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	@Column(name = "entity")
	@Type(type = "org.hibernate.type.MaterializedClobType")
	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	@Column(name = "exceptionMessage")
	@Type(type = "org.hibernate.type.MaterializedClobType")
	public String getExceptionMessage() {
		return this.exceptionMessage;
	}

	public void setExceptionMessage(String exceptionMessage) {
		this.exceptionMessage = exceptionMessage;
	}

}
