package com.kangdainfo.common.model.bo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonZip generated by hbm2java
 */

@Entity
@Table(name = "COMMON_ZIP")
public class CommonZip extends BaseModel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6858980315311997628L;

	private Integer id;
	private String zipCode; // 郵遞區號
	private String zipInfo; // 中文說明
	private String cityName; // 鄉鎮市區
	private String roadName; // 路
	private String noName; // 門牌號碼

	public CommonZip() {
	}

	public CommonZip(Integer id, String zipCode, String zipInfo,
			String cityName, String roadName, String noName, String createId,
			String createDate, String createTime, String updateId,
			String updateDate, String updateTime, String updateIp,
			String updateUnitShortName) {

		super(createId, createDate, createTime, updateId, updateDate,
				updateTime, updateIp, updateUnitShortName);

		this.id = id;
		this.zipCode = zipCode;
		this.zipInfo = zipInfo;
		this.cityName = cityName;
		this.roadName = roadName;
		this.noName = noName;
		this.createId = createId;
		this.createDate = createDate;
		this.createTime = createTime;
		this.updateId = updateId;
		this.updateIp = updateIp;
		this.updateDate = updateDate;
		this.updateTime = updateTime;		
		this.updateUnitShortName = updateUnitShortName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	@SequenceGenerator(name = "id", sequenceName = "COMMON_ZIP_SEQ")
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "zipCode", length = 5)
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "zipInfo", length = 68)
	public String getZipInfo() {
		return zipInfo;
	}

	public void setZipInfo(String zipInfo) {
		this.zipInfo = zipInfo;
	}

	@Column(name = "cityName", length = 14)
	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "roadName", length = 24)
	public String getRoadName() {
		return roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	@Column(name = "noName", length = 30)
	public String getNoName() {
		return noName;
	}

	public void setNoName(String noName) {
		this.noName = noName;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("CommonZip [id = ");
		sb.append(id);
		sb.append(", zipCode=");
		sb.append(zipCode);
		sb.append(", zipInfo=");
		sb.append(zipInfo);
		sb.append(", cityName=");
		sb.append(cityName);
		sb.append(", roadName=");
		sb.append(roadName);
		sb.append(", noName=");
		sb.append(noName);
		sb.append(", updateId=");
		sb.append(updateId);
		sb.append(", updateDate=");
		sb.append(updateDate);
		sb.append(", updateTime=");
		sb.append(updateTime);
		sb.append(", updateIp=");
		sb.append(updateIp);
		sb.append(", createId=");
		sb.append(createId);
		sb.append(", createDate=");
		sb.append(createDate);
		sb.append(", createTime=");
		sb.append(createTime);
		sb.append(", updateUnitShortName=");
		sb.append(updateUnitShortName);
		sb.append("]");

		return sb.toString();
	}
}
