package com.kangdainfo.common.model.bo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CommonCodekind generated by hbm2java
 */
@Entity
@Table(name = "COMMON_CODEKIND", uniqueConstraints = @UniqueConstraint(columnNames = "codeKindId"))
public class CommonCodeKind extends BaseModel implements java.io.Serializable {

	private static final long serialVersionUID = 106739551598507415L;
	private Integer id;
	private CommonCatalog commonCatalog;
	private String codeKindId;
	private String codeKindName;
	private String codeLabelCon1;
	private String codeLabelCon2;
	private String codeLabelCon3;
	private String memoLabel;
	private Integer codeMaxLen;
	private Set<CommonCode> commonCodes = new HashSet<CommonCode>(0);

	public CommonCodeKind() {
	}

	public CommonCodeKind(Integer id, String codeKindId, String codeKindName) {
		this.id = id;
		this.codeKindId = codeKindId;
		this.codeKindName = codeKindName;
	}

	public CommonCodeKind(Integer id, String codeKindId, String codeKindName,
			String codeLabelCon1, String codeLabelCon2, String codeLabelCon3,
			String memoLabel, Integer codeMaxLen, Set<CommonCode> commonCodes,
			CommonCatalog commonCatalog) {
		this.id = id;
		this.codeKindId = codeKindId;
		this.codeKindName = codeKindName;
		this.codeLabelCon1 = codeLabelCon1;
		this.codeLabelCon2 = codeLabelCon2;
		this.codeLabelCon3 = codeLabelCon3;
		this.memoLabel = memoLabel;
		this.codeMaxLen = codeMaxLen;
		this.commonCodes = commonCodes;
		this.commonCatalog = commonCatalog;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_CODEKIND_SEQ")	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalogId")
	public CommonCatalog getCommonCatalog() {
		return commonCatalog;
	}

	public void setCommonCatalog(CommonCatalog commonCatalog) {
		this.commonCatalog = commonCatalog;
	}
	
	@Column(name = "codeKindId", unique = true, nullable = false, length = 50)
	public String getCodeKindId() {
		return this.codeKindId;
	}

	public void setCodeKindId(String codeKindId) {
		this.codeKindId = codeKindId;
	}

	@Column(name = "codeKindName", nullable = false, length = 500)
	public String getCodeKindName() {
		return this.codeKindName;
	}

	public void setCodeKindName(String codeKindName) {
		this.codeKindName = codeKindName;
	}

	@Column(name = "codeLabelCon1", length = 100)
	public String getCodeLabelCon1() {
		return this.codeLabelCon1;
	}

	public void setCodeLabelCon1(String codeLabelCon1) {
		this.codeLabelCon1 = codeLabelCon1;
	}

	@Column(name = "codeLabelCon2", length = 100)
	public String getCodeLabelCon2() {
		return this.codeLabelCon2;
	}

	public void setCodeLabelCon2(String codeLabelCon2) {
		this.codeLabelCon2 = codeLabelCon2;
	}

	@Column(name = "codeLabelCon3", length = 100)
	public String getCodeLabelCon3() {
		return this.codeLabelCon3;
	}

	public void setCodeLabelCon3(String codeLabelCon3) {
		this.codeLabelCon3 = codeLabelCon3;
	}

	@Column(name = "memoLabel", length = 100)
	public String getMemoLabel() {
		return this.memoLabel;
	}

	public void setMemoLabel(String memoLabel) {
		this.memoLabel = memoLabel;
	}

	@Column(name = "codeMaxLen")
	public Integer getCodeMaxLen() {
		return this.codeMaxLen;
	}

	public void setCodeMaxLen(Integer codeMaxLen) {
		this.codeMaxLen = codeMaxLen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonCodeKind", cascade = CascadeType.ALL)	
	@OrderBy("codeId asc")
	public Set<CommonCode> getCommonCodes() {
		return this.commonCodes;
	}

	public void setCommonCodes(Set<CommonCode> commonCodes) {
		this.commonCodes = commonCodes;
	}

}
