package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonCode generated by hbm2java
 */
@Entity
@Table(name = "COMMON_CODE")
public class CommonCode extends BaseModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1858798498553015740L;
	private Integer id;
	private CommonCodeKind commonCodeKind;
	private String codeId;
	private String codeName;
	private String codeShortName;
	private String codeEngName;
	private String issueDate;
	private String endDate;
	private String codeCon1;
	private String codeCon2;
	private String codeCon3;
	private String codeMemo;

	public CommonCode() {
	}

	public CommonCode(Integer id, String codeId, String codeName) {
		this.id = id;
		this.codeId = codeId;
		this.codeName = codeName;
	}

	public CommonCode(int id, CommonCodeKind commonCodekind, String codeId,
			String codeName, String codeShortName, String codeEngName,
			String issueDate, String endDate, String codeCon1, String codeCon2,
			String codeCon3, String codeMemo, String updateId, String updateDate, 
			String updateTime, String updateIp, String createId, String createDate, 
			String createTime, String updateUnitShortName) {
		this.id = id;
		this.commonCodeKind = commonCodekind;
		this.codeId = codeId;
		this.codeName = codeName;
		this.codeShortName = codeShortName;
		this.codeEngName = codeEngName;
		this.issueDate = issueDate;
		this.endDate = endDate;
		this.codeCon1 = codeCon1;
		this.codeCon2 = codeCon2;
		this.codeCon3 = codeCon3;
		this.codeMemo = codeMemo;
		this.updateId = updateId;
		this.updateDate = updateDate;
		this.updateTime = updateTime;
		this.updateIp = updateIp;
		this.createId = createId;
		this.createDate = createDate;
		this.createTime = createTime;
		this.updateUnitShortName = updateUnitShortName;	
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_CODE_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codeKindId")
	public CommonCodeKind getCommonCodeKind() {
		return this.commonCodeKind;
	}

	public void setCommonCodeKind(CommonCodeKind commonCodekind) {
		this.commonCodeKind = commonCodekind;
	}

	@Column(name = "codeId", nullable = false, length = 50)
	public String getCodeId() {
		return this.codeId;
	}

	public void setCodeId(String codeId) {
		this.codeId = codeId;
	}

	@Column(name = "codeName", nullable = false, length = 500)
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "codeShortName", length = 250)
	public String getCodeShortName() {
		return this.codeShortName;
	}

	public void setCodeShortName(String codeShortName) {
		this.codeShortName = codeShortName;
	}

	@Column(name = "codeEngName", length = 500)
	public String getCodeEngName() {
		return this.codeEngName;
	}

	public void setCodeEngName(String codeEngName) {
		this.codeEngName = codeEngName;
	}

	@Column(name = "issueDate", length = 7)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "endDate", length = 7)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "codeCon1", length = 1000)
	public String getCodeCon1() {
		return this.codeCon1;
	}

	public void setCodeCon1(String codeCon1) {
		this.codeCon1 = codeCon1;
	}

	@Column(name = "codeCon2", length = 1000)
	public String getCodeCon2() {
		return this.codeCon2;
	}

	public void setCodeCon2(String codeCon2) {
		this.codeCon2 = codeCon2;
	}

	@Column(name = "codeCon3", length = 1000)
	public String getCodeCon3() {
		return this.codeCon3;
	}

	public void setCodeCon3(String codeCon3) {
		this.codeCon3 = codeCon3;
	}

	@Column(name = "codeMemo", length = 2000)
	public String getCodeMemo() {
		return this.codeMemo;
	}

	public void setCodeMemo(String codeMemo) {
		this.codeMemo = codeMemo;
	}

}
