package com.kangdainfo.common.model.bo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CommonVersion generated by hbm2java
 */
@Entity
@Table(name = "COMMON_VERSION")
public class CommonVersion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4911921432625756705L;
	private int id;
	private String bitYn;
	private String versionDescription;

	public CommonVersion() {
	}

	public CommonVersion(int id) {
		this.id = id;
	}

	public CommonVersion(int id, String bitYn, String versionDescription) {
		this.id = id;
		this.bitYn = bitYn;
		this.versionDescription = versionDescription;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bitYN", length = 50)
	public String getBitYn() {
		return this.bitYn;
	}

	public void setBitYn(String bitYn) {
		this.bitYn = bitYn;
	}

	@Column(name = "versionDescription", length = 50)
	public String getVersionDescription() {
		return this.versionDescription;
	}

	public void setVersionDescription(String versionDescription) {
		this.versionDescription = versionDescription;
	}

}
