package com.kangdainfo.common.model.bo;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommonMsg generated by hbm2java
 */
@Entity
@Table(name = "COMMON_MSG")
public class CommonMsg extends BaseModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7658109880027482071L;
	private Long id;
	private String startDate;
	private String startTime;
	private String endDate;
	private String endTime;
	private String isOpen;
	private String deptCode;
	private String userId;
	private String msgBody;
	private String msgSender;
	private Set<CommonMsgGroup> commonMsgGroups = new HashSet<CommonMsgGroup>(0);
	private Set<CommonMsgLog> commonMsgLogs = new HashSet<CommonMsgLog>(0);

	public CommonMsg() {
	}

	public CommonMsg(Long id) {
		this.id = id;
	}

	public CommonMsg(Long id, String startDate, String startTime,
			String endDate, String endTime, String isOpen, String deptCode,
			String userId, String msgBody, String msgSender, String editId,
			String editDate, String editTime,
			Set<CommonMsgGroup> commonMsgGroups, Set<CommonMsgLog> commonMsgLogs) {
		this.id = id;
		this.startDate = startDate;
		this.startTime = startTime;
		this.endDate = endDate;
		this.endTime = endTime;
		this.isOpen = isOpen;
		this.deptCode = deptCode;
		this.userId = userId;
		this.msgBody = msgBody;
		this.msgSender = msgSender;
		this.commonMsgGroups = commonMsgGroups;
		this.commonMsgLogs = commonMsgLogs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="id", sequenceName = "COMMON_MSG_SEQ")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "startDate", length = 7)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "startTime", length = 6)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "endDate", length = 7)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "endTime", length = 6)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "isOpen", length = 1)
	public String getIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(String isOpen) {
		this.isOpen = isOpen;
	}

	@Column(name = "deptCode", length = 10)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "userId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "msgBody", length = 2000)
	public String getMsgBody() {
		return this.msgBody;
	}

	public void setMsgBody(String msgBody) {
		this.msgBody = msgBody;
	}

	@Column(name = "msgSender", length = 50)
	public String getMsgSender() {
		return this.msgSender;
	}

	public void setMsgSender(String msgSender) {
		this.msgSender = msgSender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonMsg", cascade = CascadeType.ALL)
	public Set<CommonMsgGroup> getCommonMsgGroups() {
		return this.commonMsgGroups;
	}

	public void setCommonMsgGroups(Set<CommonMsgGroup> commonMsgGroups) {
		this.commonMsgGroups = commonMsgGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonMsg", cascade = CascadeType.ALL)
	public Set<CommonMsgLog> getCommonMsgLogs() {
		return this.commonMsgLogs;
	}

	public void setCommonMsgLogs(Set<CommonMsgLog> commonMsgLogs) {
		this.commonMsgLogs = commonMsgLogs;
	}

}
